# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- group: EPlast
  # Container registry service connection established during pipeline creation
- name: dockerRegistryServiceConnection
  value: '6c4d5954-410a-4604-8404-40b91e3fedb7'
- name: imageRepository
  value: 'eplastweb'
- name: containerRegistry
  value: 'eplastregistry.azurecr.io'
- name: dockerfilePath
  value: '**/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: imagePullSecret
  value: 'eplastregistry14394d69-auth'
  # Name of the new namespace being created to deploy the PR changes.
- name: k8sNamespaceForPR
  value: 'review-app-$(System.PullRequest.PullRequestId)'

  # Agent VM image name
pool:
  name: vmss-pipeline
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: vmss-pipeline
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        # Write your commands here
        cat > src/config.ts << EOF
        const BASE_URL = "https://eplastprd.westeurope.cloudapp.azure.com/api/";
        export default BASE_URL;
        EOF
        cat src/config.ts
      displayName: 'Update API URL'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      name: vmss-pipeline
      vmImage: 'ubuntu-latest'
    environment: 'Eplastfrontend.eplast'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: Replace tokens in **/*
            inputs:
              rootDirectory: $(Pipeline.Workspace)/manifests
              targetFiles: '**/*.yml'
              keepToken: true
              tokenPrefix: ___
              tokenSuffix: ___ 
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/ingress-prod.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

