apiVersion : apps/v1
kind: Deployment
metadata:
  name: eplastweb
  labels:
    app: eplastweb  
spec:
  selector:
    matchLabels:
      app: eplastweb
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: eplastweb 
    spec:
      containers:
        - name: eplastweb 
          image: ___containerRegistry___/eplastweb
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"         
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: eplastweb
spec:
    type: ClusterIP
    ports:
    - port: 80
    selector:
        app: eplastweb

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: eplastweb-autoscaler
#   namespace: eplast
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: eplastweb
#   minReplicas: 1
#   maxReplicas: 2
#   targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: eplastweb-autoscaler
  namespace: eplast
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eplastweb
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50